### ISSUE TITLE
[1.14.4] Crash when server is done booting.

### ISSUE THREAD

**Issue by Gbergz** [hm-ysjiang/PotionCapsule#10]
**Describe the bug**
Server will start then instantly close upon being online for 15 seconds.

**To Reproduce**
1. Have the mod installed
2. Start an existing server.
3. It crashes.
4. ? Profit

**Expected behavior**
Not to crash while starting the server.

**Information :**
 - *Mod Version:* 1.2.3
 - *Forge Version:* 28.1.107
 - *Crash Log:* https://gist.github.com/Gbergz/9b34b964000a08b65cf743ad1058e086

**Additional context**
To be honest I don't think this has anything to do with your mod.
I think it has something to do with the [SpikeTraps](https://www.curseforge.com/minecraft/mc-mods/spike-traps) mod. Not entirely sure, but I reported in both places just to be safe. Since I could see both of your mod in the stacktrace.

**Comment by hm-ysjiang** [comment]
Well, I think this is my fault.

I query all the active effects from registered potions when the item group(creative menu) is being filled, which is only happening on the client side. And the vanilla monster drop seems to be also happening on the client side, so it doesn't crash the game.
The crashing call from SpikeTraps is on server side, though. That's why it crashes the game.

I'll work on to fix this bug in the next version, thanks for your report.

**Comment by hm-ysjiang** [comment]
Fix available in 1.2.4
